### ISSUE TITLE
Problem with spend money from Multibit

### ISSUE THREAD

**Issue by Baronchik** [bitcoin-solutions/multibit#721] opened 2015-08-13 06:36 UTC
Tell me what is happening with a purse. For the second time in a row to send money to the recipient but they did not reach. Do you have some sort of support. What would decide my problem? For the first time I sent $ 5, but for about a month, they have never reached. And yesterday sent 40 dollars but they also did not reach the recipient.

**Comment by jim618** [comment] 2015-08-13 11:27
Hi Baronchik,
Can you attach a screenshot of your Transactions screen please so that we can have a look at it please.

**Comment by Baronchik** [comment] 2015-08-13 11:40
Screenshot from multibit,or screenshot transaction on blockchain.info?

**Comment by Baronchik** [comment] 2015-08-13 12:00
![12213123](https://cloud.githubusercontent.com/assets/13551831/9249281/064c81aa-41cc-11e5-8579-9cfbe041e792.png)

**Comment by jim618** [comment] 2015-08-13 12:38
That transaction looks perfectly ok.
There are 4 steps in sending a transaction from Person A to Person B

1) Person A uses MultiBit to create a transaction and transmits it to the Bitcoin network
2) The Bitcoin network relays the transaction to all the nodes
3) Person B picks up the unconfirmed transaction from the Bitcoin network and it appears in their wallet.
4) (Some time later) the transaction appears in a block and hence is confirmed.

From your description in the OP:
1) Transaction has been transmitted successfully (blockchain.info has it in their database)
2) Yes, the transaction is definitely broadcast and relayed (same reason as 1)
3) Person B picking up the transaction is obviously dependent on THEIR wallet software.
4) Yes, the transaction is confirmed.

If the transaction is sent from MultiBit and you can see it confirmed on blockchain.info then it really has been sent. You can point to the blockchain.info entry as evidence that it was sent correctly.

If the recipient does not have it in their wallet then they need to fix it at their end. You sent it correctly.

This issue is a repeat of the the earlier one you raised where the transaction was also sent ok so I am not sure what else to say.

**Comment by Baronchik** [comment] 2015-08-13 12:46
The problem in my purse, as with other purses to the same recipient receives the money.

**Comment by Baronchik** [comment] 2015-08-13 12:57
How can I solve my problem? You support Multibit purse. Help solve the problem. The last time this month the money did not come, but I did not do anything because the amount is small, but this time amount is more.

**Comment by Baronchik** [comment] 2015-08-13 13:38
blockchain.info has it in their database, but blockexplorer.com dont have in their database.
![11111111](https://cloud.githubusercontent.com/assets/13551831/9251013/abe34ce0-41d9-11e5-972c-8e41d323fbe3.png)

**Comment by gary-rowe** [comment] 2015-08-13 20:51
The following block chain explorers confirm that MultiBit correctly sent the transaction and it is present on the block chain:

* [Blockchain.info](https://blockchain.info/tx/0278d236ff32f1d90202d0d9a9ff64848141f447b4fed07163ef206035d1eb46)
* [BitPay Insight](https://insight.bitpay.com/tx/0278d236ff32f1d90202d0d9a9ff64848141f447b4fed07163ef206035d1eb46)

Blockchain explorer has been broken for a while (the latest block it shows is 1st June 2015) so its results cannot be trusted.

If the person receiving the funds is complaining that they do not have them, then they need to check their wallet that they own the private keys for address: 1EJC5s29pXNLwzxtA62T6BoVnUErh7jsMU which has the bulk of the bitcoin sent in that transaction.

Once again, since this transaction was successfully signed and accepted by the Bitcoin network and mined deeply into the block chain MultiBit is not at fault. There is nothing we can do.

Closing.

**Closed by gary-rowe** 2015-08-13 20:51 UTC
