### ISSUE TITLE
multibit error another programs changed this wallet to avoid errors this multibit has stopped updating

### ISSUE THREAD

**Issue by Igorek3** [bitcoin-solutions/multibit#704] opened 2015-06-20 12:02 UTC
Hi guys,
I was reading all possible articles about this issue "multibit error another programs changed this wallet to avoid errors this multibit has stopped updating" and all advises did not work for me.

On my MultiBit wallet I have bitcoin dust and it takes me a couple hours to load. Most of times its is not loading at all and i need to restart my wallet.
1. I am using Mac. Tried to copy created .wallet for windows, did not even recognize the wallet. 
2. I have never change location of original .wallet file since i created it in MultiBit.
3. When my wallet with all dust bitcoins finally loaded i tried to send them many times to another wallet and always i have the same issue "multibit error another programs changed this wallet to avoid errors this multibit has stopped updating".
4. I was even tried to export a private key of my wallet and it never work, every time the same message.

!!!PLEASE!!! Can anyone help me to solve this problem as i have god bit of bitcoins mined for the last year. Will be very appreciate.
Is it any other way i can at least find out the private key of my wallet?

**Comment by jim618** [comment] 2015-06-20 12:47
MultiBit wallets are identical across Mac/ Windows/ Linux so in step one you should be able to just be able to do a File | Open to open the wallet.

**Comment by Igorek3** [comment] 2015-06-20 12:55
Thanks Jim, yes i know that but in my case is not opening in windows. Anyway, i was opening this file across 2 macs computers and it is working, slowly but opening and loading my bitcoins. The main issue is to sent the to another wallet or export private key. Always the same message

**Comment by jim618** [comment] 2015-07-20 14:56
Dupe of #693

**Comment by gary-rowe** [comment] 2015-07-29 13:16
Closing as dupe.

**Closed by gary-rowe** 2015-07-29 13:16 UTC
Labels: awaiting issue
