### ISSUE TITLE
Unconfirmed/pending transaction no longer exists after blockchain reset, coins gone!

### ISSUE THREAD

**Issue by shanerm** [bitcoin-solutions/multibit#739] opened 2015-11-20 22:46 UTC
Last night, I sent some coin from one location into my Multibit wallet. It worked fine. Then I tried to send some from my Multibit wallet to another location. It came up as "unconfirmed/pending". After a few hours, I exported my transactions to keep a record, then reset the blockchain and transactions. Now the last transaction is missing, along with my coin that I sent. The TXID is invalid and doesn't show up on blockchain or blockexplorer. Is there anything I can do to recover my coin?

**Comment by jim618** [comment] 2015-11-21 12:18
Duplicate of:
http://bitcoin.stackexchange.com/questions/41448/unconfirmed-pending-transaction-in-multibit-no-longer-exists-but-my-coin-is-sti/41455#41455

Answered there

**Closed** 2015-11-22 10:16 UTC

**Comment by shanerm** [comment] 2015-11-22 18:36
Wow. Useless assholes.

**Comment by gary-rowe** [comment] 2015-11-22 19:01
What's useless about it? Following the instructions in our help here:

https://multibit.org/en/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html

tells you what to do.

**Comment by shanerm** [comment] 2015-11-22 19:22
I already said it didn't help me. I've been over that site several times
before I even came here. It does not explain what to do when I have a TXID
that doesn't show up in the blockchain but is only appearing in the records
of my wallet.
